### PR TITLE
Andrey-Shmiglov-comp-math-2

### PR DESCRIPTION
**Pull request by gandreymaster**

### CODE REVIEW

**Comment by gandreymaster** [comment]
hello

**Comment by BlackfyreInc** [comment]
hi

**Comment by gandreymaster** [comment]
> hi

hello there

**Comment by BlackfyreInc** [comment]
General Kenobi

**Review by mecchmatProjects — COMMENTED** [review]
+1

**Review by mecchmatProjects — APPROVED** [review]

**Pull request merged**
